# Generated by Django 2.2.1 on 2021-03-13 04:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='post',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Publicado/No publicado'),
        ),
    ]
